'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const crypto = require('node:crypto');
const { chromium } = require('playwright-core');
const { Hub } = require('../packages/hub/server');
const { Runtime } = require('../packages/runtime');
const { Endpoint } = require('../packages/e2ee/endpoint');
const root = path.resolve(__dirname, '..'), out = path.join(root, '.artifacts/pilot-browser');
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'plexus-pilot-ui-'));
const checks = [], errors = [], logs = [];
let hub, runtime, browser, alice, hostKeys, options;
const until = async (read, label) => {
  const deadline = Date.now() + 45000;
  while (Date.now() < deadline) { const value = await read(); if (value) return value; await new Promise(resolve => setTimeout(resolve, 100)); }
  throw new Error('Timed out: ' + label + '\n' + logs.slice(-10).join('\n'));
};
const pass = name => { checks.push(name); console.log('PASS ' + name); };
const capture = async (page, name, selector = '#pilot-setup', mobile = false) => {
  await page.setViewportSize(mobile ? { width: 390, height: 844 } : { width: 1487, height: 1058 });
  await page.emulateMedia({ reducedMotion: 'reduce' }); await page.evaluate(() => document.fonts.ready);
  await page.locator(selector).evaluate(node => node.scrollIntoView({ block: 'start' }));
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  if (selector === '.pilot-dialog') {
    assert.equal(await page.locator(selector).evaluate(node => {
      const box = node.getBoundingClientRect();
      return Math.abs((box.left + box.right) / 2 - innerWidth / 2) <= 1 && box.top >= 0 && box.bottom <= innerHeight;
    }), true, 'dialog is centered and fits the viewport');
  }
  await page.screenshot({ path: path.join(out, name + '.png') });
};
const click = (page, action) => page.locator('[data-action="' + action + '"]').click();
async function consent(page) {
  await page.locator('#nav-fleet').click();
  await page.getByLabel('Allow content-free product measurement').check();
  await until(async () => (await page.locator('#pilot-setup').innerText()).includes('Enabled for your account'), 'measurement consent saved');
}
(async () => {
  fs.mkdirSync(out, { recursive: true });
  const workspace = path.join(dir, 'project'); fs.mkdirSync(workspace);
  hub = new Hub({ dbFile: path.join(dir, 'hub.sqlite'), staticDir: path.join(root, 'apps/web') });
  const address = await hub.listen(), url = 'http://127.0.0.1:' + address.port;
  options = { hubUrl: url.replace('http', 'ws'), dataDir: path.join(dir, 'host'), projects: [workspace], encryptedTasksOnly: true,
    encryptedEndpointFactory: async value => {
      hostKeys ||= await Endpoint.create(value); hostKeys.transport = value.transport;
      return Object.assign(Object.create(hostKeys), { close: async () => {} });
    }, log: value => logs.push(value) };
  runtime = new Runtime(options); await runtime.start();
  browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH, headless: true });
  alice = await browser.newPage({ viewport: { width: 1487, height: 1058 } }); alice.on('pageerror', error => errors.push(error.message));
  await alice.goto(url); await alice.locator('#login-name').fill('Alice'); await alice.locator('#login-form button').click();
  await alice.locator('#team-name').fill('Private pilot'); await alice.locator('#btn-create-team').click();
  await alice.locator('#encrypted-setup').filter({ hasText: 'This endpoint: verified' }).waitFor({ timeout: 30000 });
  await alice.locator('[data-action="preview-diagnostics"]').waitFor();
  const account = await alice.evaluate(() => window.__plexus.state.me);
  const teamId = await alice.evaluate(() => window.__plexus.state.teamId);
  assert.equal(hub.store.db.prepare('SELECT COUNT(*) n FROM measurement_events').get().n, 0);
  await capture(alice, 'setup-missing-host');
  await click(alice, 'preview-diagnostics');
  const report = JSON.parse(await alice.locator('.pilot-export').innerText());
  assert.equal(report.stages.find(row => row.stage === 'project').code, 'runtime_missing');
  assert.doesNotMatch(JSON.stringify(report), new RegExp(account.token + '|' + account.id + '|Private pilot|Alice'));
  await capture(alice, 'diagnostic-preview', '.pilot-dialog');
  await capture(alice, 'diagnostic-preview-mobile', '.pilot-dialog', true);
  const downloadPromise = alice.waitForEvent('download'); await click(alice, 'download-diagnostics');
  const download = await downloadPromise; const saved = path.join(out, 'reviewed-diagnostics.json'); await download.saveAs(saved);
  assert.deepEqual(JSON.parse(fs.readFileSync(saved, 'utf8')), report); await click(alice, 'close-pilot-dialog');
  await alice.setViewportSize({ width: 1487, height: 1058 });
  pass('onboarding identifies a missing host; inspected download contains only allowlisted diagnostics and no automatic measurement');
  await consent(alice);
  await until(() => runtime.pairingCode, 'pairing code');
  await alice.locator('#pair-code').fill(runtime.pairingCode); await alice.locator('#btn-pair-host').click();
  await until(() => runtime.teamId, 'paired host');
  const identity = await alice.evaluate(() => window.__plexus.state.encryptedIdentity);
  options.encryptionAuthority = { ...identity, teamId }; options.approvalAuthority = { ...identity, teamId };
  runtime.encryptionAuthority = options.encryptionAuthority; runtime.approvalAuthority = options.approvalAuthority;
  await runtime.ensureEncryptedHost();
  await click(alice, 'show-host-fingerprint'); await click(alice, 'confirm-host');
  await alice.locator('#provider-select').selectOption('demo');
  await require('./pilot-ui-states')(alice, out);
  await alice.locator('#input').fill('create PRIVATE-CANARY.txt'); await alice.locator('#btn-send').click();
  await alice.locator('.ew-file h4').filter({ hasText: 'PRIVATE-CANARY.txt' }).waitFor({ timeout: 45000 });
  const taskId = await alice.evaluate(() => window.__plexus.state.activeThreadId);
  const task = hub.encryptedTasks.get(taskId);
  await until(() => hub.pilot.summary(teamId).counts.solo === 1, 'solo outcome measured');
  assert.equal(hub.pilot.summary(teamId).activatedPeople, 0);
  pass('a successful solo task is measured without activating anyone');
  const bob = await browser.newPage({ viewport: { width: 1487, height: 1058 } }); bob.on('pageerror', error => errors.push(error.message));
  await bob.goto(url); await bob.locator('#login-name').fill('Bob'); await bob.locator('#login-form button').click();
  await bob.locator('#team-gate:not(.hidden)').waitFor(); const bobId = await bob.locator('#team-gate-account-id').inputValue();
  await alice.locator('#nav-fleet').click(); await alice.locator('#invitee-user-id').fill(bobId); await alice.locator('#btn-invite').click();
  await alice.locator('#invite-row:not(.hidden)').waitFor();
  await bob.locator('#join-code').fill(await alice.locator('#invite-code').inputValue()); await bob.locator('#btn-join-team').click();
  await bob.locator('#enrollment-badge').waitFor();
  await alice.locator('#btn-access').click();
  const bobDevice = alice.locator('.ew-device').filter({ hasText: 'Bob' }); await bobDevice.locator('input[type="checkbox"]').check();
  await bobDevice.locator('[data-action="verify-teammate"]').click(); await bobDevice.locator('[data-action="grant-project"]').click();
  await bob.locator('#encrypted-setup').filter({ hasText: 'This endpoint: verified' }).waitFor({ timeout: 45000 });
  await bob.locator('#btn-access').click(); await click(bob, 'confirm-team-authority');
  await consent(bob);
  await bob.locator('.encrypted-task-row').click(); await click(bob, 'verify-task-host'); await click(bob, 'confirm-host');
  await bob.locator('.ew-file h4').filter({ hasText: 'PRIVATE-CANARY.txt' }).waitFor({ timeout: 45000 });
  assert.equal(hub.pilot.summary(teamId).activatedPeople, 0);
  assert.equal(await bob.locator('[data-action="delete-task"]').count(), 0);
  await bob.locator('#ew-target').filter({ hasText: 'Start a follow-up' }).waitFor();
  await bob.locator('#input').fill('create TEAM-RESULT.txt'); await bob.locator('#btn-send').click();
  await bob.locator('.ew-file h4').filter({ hasText: 'TEAM-RESULT.txt' }).waitFor({ timeout: 45000 });
  await alice.locator('.encrypted-task-row').click();
  await until(() => hub.pilot.summary(teamId).activatedPeople === 2, 'two humans activated after real delivered followup');
  const initial = hub.pilot.summary(teamId).counts.activation; await bob.reload(); await bob.locator('.encrypted-task-row').click();
  await bob.locator('.ew-file h4').filter({ hasText: 'TEAM-RESULT.txt' }).waitFor({ timeout: 45000 });
  assert.equal(hub.pilot.summary(teamId).counts.activation, initial);
  const measured = hub.store.db.prepare('SELECT record FROM measurement_events').all().map(row => row.record).join('\n');
  assert.doesNotMatch(measured, /PRIVATE-CANARY|TEAM-RESULT|\.txt|Alice|Bob/);
  pass('passive reading does not activate; actual peer execution activates both humans and reload deduplicates content-free reports');
  const authorization = () => JSON.stringify(['memberships', 'project_grants', 'endpoint_enrollments', 'approvers'].map(table => hub.store.db.prepare('SELECT * FROM ' + table).all()));
  const beforeSeats = authorization();
  const seat = { id: crypto.randomBytes(16).toString('hex'), teamId, userId: bobId, billingOwnerId: account.id, operatorId: account.id,
    status: 'active', payment: 'paid', price: null, currency: null, expectedRevision: 0 };
  hub.pilot.recordSeat(seat); await alice.locator('#btn-access').click();
  await alice.locator('[data-pilot-seats] .pilot-seat-row').filter({ hasText: 'Bob' }).filter({ hasText: 'Payment: paid' }).waitFor({ timeout: 30000 });
  await capture(alice, 'paid-seat-access', '[data-pilot-seats]');
  hub.pilot.recordSeat({ ...seat, id: crypto.randomBytes(16).toString('hex'), status: 'revoked', expectedRevision: 1 });
  await alice.locator('[data-pilot-seats] .pilot-seat-row').filter({ hasText: 'Bob' }).filter({ hasText: 'Seat: revoked' }).waitFor({ timeout: 30000 });
  assert.equal(authorization(), beforeSeats);
  pass('customer-visible paid and revoked seats leave membership, keys, project access and approval grants unchanged');
  await alice.locator('#nav-fleet').click(); await capture(alice, 'setup-desktop'); await capture(alice, 'setup-mobile', '#pilot-setup', true);
  await alice.setViewportSize({ width: 1487, height: 1058 });
  const beforeDelete = hub.retention.snapshot();
  await runtime.stop();
  await alice.locator('.encrypted-task-row').click();
  await click(alice, 'delete-task');
  assert.equal(await alice.locator('[data-action="confirm-delete"]').isDisabled(), true);
  await capture(alice, 'delete-confirmation', '.pilot-dialog');
  await capture(alice, 'delete-confirmation-mobile', '.pilot-dialog', true);
  await alice.setViewportSize({ width: 1487, height: 1058 });
  await alice.getByLabel('I understand deletion and the recovery archive consequences').check(); await click(alice, 'confirm-delete');
  await until(() => hub.encryptedTasks.get(taskId) === null, 'service task deletion');
  await alice.locator('[data-pilot-deletion] [data-state="pending"]').waitFor({ timeout: 30000 });
  await capture(alice, 'deletion-offline', '[data-pilot-deletion]');
  assert.equal(hub.retention.restore(beforeDelete).restored, 0);
  await bob.reload(); await bob.locator('#app:not(.hidden)').waitFor(); assert.equal(await bob.locator('.encrypted-task-row').count(), 0);
  pass('owner deletion works while the host is offline, removes teammate navigation and survives service restore');
  runtime = new Runtime(options); await runtime.start();
  await until(() => hub.retention.list(teamId)[0]?.pendingHosts.length === 0, 'host applies deletion after restart');
  assert.ok(runtime.encryptedHost.state.load('deleted:' + taskId));
  assert.equal(runtime.encryptedHost.state.load('execution:' + taskId), null);
  assert.ok(fs.existsSync(path.join(workspace, 'PRIVATE-CANARY.txt')));
  await alice.locator('[data-pilot-deletion] [data-state="applied"]').waitFor({ timeout: 30000 });
  await capture(alice, 'deletion-applied', '[data-pilot-deletion]');
  pass('reconnected production host erases task state, preserves a durable deletion fence and reports a signed receipt while retaining project files');
  fs.mkdirSync(path.join(workspace, 'build')); fs.writeFileSync(path.join(workspace, 'build', 'retain.txt'), 'retained');
  await alice.locator('#nav-fleet').click(); await alice.locator('#input').fill('delete build'); await alice.locator('#btn-send').click();
  await alice.locator('[data-action="encrypted-approval-accept"]').waitFor({ timeout: 45000 });
  const liveTaskId = await alice.evaluate(() => window.__plexus.state.activeThreadId);
  assert.ok(runtime.encryptedExecution.active.has(liveTaskId));
  await alice.locator('#btn-access').click();
  await click(alice, 'delete-project');
  await alice.getByLabel('I understand deletion and the recovery archive consequences').check(); await click(alice, 'confirm-delete');
  await until(() => hub.retention.deleted(teamId, task.projectId), 'project offboarded');
  await until(() => !runtime.encryptedHost.projects.has(task.projectId), 'host removes project mapping');
  await until(() => !runtime.encryptedExecution.active.has(liveTaskId) && runtime.encryptedHost.state.load('execution:' + liveTaskId) === null, 'offboarding cancels the pending approval and clears execution');
  assert.ok(fs.existsSync(path.join(workspace, 'build', 'retain.txt')), 'offboarding cannot approve the pending deletion');
  assert.equal(hub.enrollment.participant(teamId, task.projectId, bobId), null);
  await runtime.stop(); runtime = new Runtime(options);
  assert.equal(runtime.encryptedProjects.has(task.projectId), false, 'offboarded project stays absent before the reconstructed host reconnects');
  await runtime.start();
  pass('project offboarding cancels an active approval, revokes grants and preserves the retired mapping across host reconstruction');
  await alice.locator('#nav-fleet').click(); await alice.getByLabel('Allow content-free product measurement').uncheck();
  await until(() => hub.pilot.consent(account.id).enabled === 0, 'measurement disabled');
  assert.equal(hub.store.db.prepare('SELECT COUNT(*) n FROM measurement_events WHERE user_id=?').get(account.id).n, 0);
  assert.deepEqual(errors, []);
  fs.writeFileSync(path.join(out, 'results.json'), JSON.stringify({ checks, errors, provider: 'deterministic demo through production Runtime' }, null, 2));
})().catch(async error => {
  console.error(error); process.exitCode = 1;
  if (alice) { await alice.screenshot({ path: path.join(out, 'failure.png') }).catch(() => {}); fs.writeFileSync(path.join(out, 'failure-page.txt'), await alice.locator('body').innerText()); }
  fs.writeFileSync(path.join(out, 'failure.json'), JSON.stringify({ error: error.stack, checks, errors, logs }, null, 2));
}).finally(async () => { await browser?.close(); await runtime?.stop(); hostKeys?.close(); await hub?.close(); fs.rmSync(dir, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 }); });
